// Starter body plans and pre-trained brains. Node 0 is the head (gets the eye).
// Units: meters, y up, ground at y = 0. All face +x (the running direction).
//
// The trained brains live in brains.ts, generated by `npm run train:creature`.
import type { BodyPlan } from './physics';
import type { Localized } from '../../lib/i18n';

export type PresetId = 'Doggo' | 'Wiggler' | 'Hopper' | 'Stickman';
/** Crowns are per kind of body: the presets, and everything drawn or edited. */
export type BodyKind = PresetId | 'Own';

export interface Preset {
  id: PresetId;
  emoji: string;
  plan: BodyPlan;
}

const bone = (a: number, b: number) => ({ a, b, muscle: false });
const flex = (a: number, b: number) => ({ a, b, muscle: true });

/** Four-legged friend: rigid body box, swinging legs, bobbing head, wagging tail. */
const doggo: BodyPlan = {
  kind: 'Doggo',
  nodes: [
    { x: 1.15, y: 1.2 }, // 0 head
    { x: 0.0, y: 0.6 }, // 1 rear hip
    { x: 0.9, y: 0.6 }, // 2 front hip
    { x: 0.9, y: 1.0 }, // 3 front shoulder
    { x: 0.0, y: 1.0 }, // 4 rear shoulder
    { x: 0.05, y: 0.07 }, // 5 rear foot
    { x: 0.95, y: 0.07 }, // 6 front foot
    { x: -0.3, y: 1.15 }, // 7 tail tip
  ],
  sticks: [
    bone(1, 2),
    bone(2, 3),
    bone(3, 4),
    bone(4, 1),
    bone(1, 3), // body brace
    bone(3, 0), // neck
    bone(1, 5), // rear leg
    bone(2, 6), // front leg
    flex(4, 0), // head bob
    flex(2, 5), // rear leg swing
    flex(1, 6), // front leg swing
    flex(4, 7), // tail wag
  ],
};

/** Inchworm: a zigzag chain that is all muscle. */
const wiggler: BodyPlan = {
  kind: 'Wiggler',
  nodes: [
    { x: 1.4, y: 0.12 }, // 0 head
    { x: 1.05, y: 0.5 },
    { x: 0.7, y: 0.12 },
    { x: 0.35, y: 0.5 },
    { x: 0.0, y: 0.12 },
  ],
  sticks: [flex(0, 1), flex(1, 2), flex(2, 3), flex(3, 4), flex(0, 2), flex(2, 4), bone(1, 3)],
};

/** Frog: triangle body, one folding back leg, one little arm. */
const hopper: BodyPlan = {
  kind: 'Hopper',
  nodes: [
    { x: 0.5, y: 0.9 }, // 0 head
    { x: 0.0, y: 0.55 }, // 1 hip
    { x: 0.7, y: 0.45 }, // 2 chest
    { x: -0.4, y: 0.3 }, // 3 knee
    { x: -0.05, y: 0.07 }, // 4 back foot
    { x: 0.8, y: 0.07 }, // 5 front foot
  ],
  sticks: [
    bone(0, 1),
    bone(0, 2),
    bone(1, 2),
    bone(1, 3), // thigh
    bone(3, 4), // shin
    bone(2, 5), // arm
    flex(1, 4), // leg fold / kick
    flex(3, 2), // leg swing
    flex(1, 5), // arm swing
  ],
};

/**
 * Two legs. It cannot stand (relaxed, it falls over in a third of a second, and
 * a sine-wave brain cannot balance), so it learns to scoot. With the old,
 * limitless muscles it learned to cartwheel instead.
 */
const stickman: BodyPlan = {
  kind: 'Stickman',
  nodes: [
    { x: 0.08, y: 1.75 }, // 0 head
    { x: 0.0, y: 1.45 }, // 1 shoulder
    { x: 0.0, y: 0.95 }, // 2 hip
    { x: 0.12, y: 0.5 }, // 3 knee
    { x: -0.12, y: 0.5 }, // 4 knee
    { x: 0.2, y: 0.07 }, // 5 foot
    { x: -0.2, y: 0.07 }, // 6 foot
  ],
  sticks: [
    bone(0, 1),
    bone(1, 2), // torso
    bone(2, 3),
    bone(2, 4), // thighs
    bone(3, 5),
    bone(4, 6), // shins
    flex(1, 3), // hip swing
    flex(1, 4),
    flex(2, 5), // knee fold
    flex(2, 6),
  ],
};

export const PRESETS: Preset[] = [
  { id: 'Doggo', emoji: '🐕', plan: doggo },
  { id: 'Wiggler', emoji: '🐛', plan: wiggler },
  { id: 'Hopper', emoji: '🐸', plan: hopper },
  { id: 'Stickman', emoji: '🧍', plan: stickman },
];

export function preset(id: PresetId): Preset {
  return PRESETS.find((p) => p.id === id)!;
}

/** Display names for the presets and the drawn bodies. */
export const KIND_NAMES: Localized<Record<BodyKind, string>> = {
  en: { Doggo: 'Doggo', Wiggler: 'Wiggler', Hopper: 'Hopper', Stickman: 'Stick-man', Own: 'Own design' },
  nl: { Doggo: 'Hondje', Wiggler: 'Kruipertje', Hopper: 'Springer', Stickman: 'Stokmannetje', Own: 'Eigen ontwerp' },
  no: { Doggo: 'Vovven', Wiggler: 'Makken', Hopper: 'Hopperen', Stickman: 'Pinnemann', Own: 'Eget design' },
};

export const KIND_EMOJI: Record<BodyKind, string> = { Doggo: '🐕', Wiggler: '🐛', Hopper: '🐸', Stickman: '🧍', Own: '✏️' };

/** Built-in champions: who wears each crown before any kid has raced that body today. */
export const ROBO_NAMES: Record<PresetId, string> = {
  Doggo: 'ROBO-PUP',
  Wiggler: 'ROBO-WORM',
  Hopper: 'ROBO-FROG',
  Stickman: 'ROBO-STICK',
};

export function clonePlan(plan: BodyPlan): BodyPlan {
  return {
    kind: plan.kind,
    nodes: plan.nodes.map((n) => ({ ...n })),
    sticks: plan.sticks.map((s) => ({ ...s })),
  };
}

export function kindOf(plan: BodyPlan): BodyKind {
  return PRESETS.some((p) => p.id === plan.kind) ? (plan.kind as PresetId) : 'Own';
}

/** The course of the delve's flat-versus-bumps demo and of round 3 (the same for every kid). */
export const COURSE_SEED = 777;
