# Data prep for Weather Detective (app/src/games/detective/). Run once:
#
#   julia --project=tools/detective tools/detective/prep.jl NC_DIR EUROPE_DIR
#
# NC_DIR     the four KNMI NetCDF maps of last year's Science Day game
#            (github.com/rik-stra/CWI_gp_temp_scienceday, data/*.nc)
# EUROPE_DIR the KNMI project's processed station arrays for 2020-06-20
#            (gp_package/data/processed/2020-06-20)
#
# Writes app/src/games/detective/data.ts: base64 blobs the game decodes at
# load time (a lazily imported chunk, so it works offline). Nothing here needs
# to be exact: the Netherlands grids are block-averaged to half resolution and
# quantised to bytes; the official European stations are jittered and the
# home stations are synthetic (see below).

using NCDatasets, NPZ, Base64, Random, Statistics

const NC_DIR = get(ARGS, 1, "nc")
const EU_DIR = get(ARGS, 2, "europe")
const OUT = joinpath(@__DIR__, "..", "..", "app", "src", "games", "detective", "data.ts")

const DAYS = [
    ("heatwave", "202507011620"),
    ("seabreeze", "202507141150"),
    ("newyear", "202501010010"),
    ("frost", "202502180810"),
]

field(ds, name) = Float64.(coalesce.(ds[name][:, :, 1], NaN))

# 2x2 block mean over land cells (NaN where a block has no land).
function halve(A, land)
    nx, ny = size(A) .÷ 2
    B = fill(NaN, nx, ny)
    for j in 1:ny, i in 1:nx
        s = 0.0; n = 0
        for dj in 0:1, di in 0:1
            a, b = 2i - 1 + di, 2j - 1 + dj
            if land[a, b] && !isnan(A[a, b])
                s += A[a, b]; n += 1
            end
        end
        n > 0 && (B[i, j] = s / n)
    end
    B
end

# Row-major bytes, north row first (screen order).
rowmajor(A) = vec(reverse(A; dims = 2))

quant(A, lo, hi) = UInt8[isnan(a) ? 0xff : round(UInt8, clamp((a - lo) / (hi - lo), 0, 1) * 254) for a in A]

function bitpack(bits)
    out = zeros(UInt8, cld(length(bits), 8))
    for (k, b) in enumerate(bits)
        b && (out[(k - 1) ÷ 8 + 1] |= UInt8(1) << ((k - 1) % 8))
    end
    out
end

b64(bytes) = base64encode(bytes)

lines = String[]
push!(lines, "// Generated by tools/detective/prep.jl. Do not edit by hand.")
push!(lines, "// Temperature maps: KNMI high-resolution weather maps (via Rik Hoekstra's 2025")
push!(lines, "// Science Day game), block-averaged to half resolution. Europe: station positions of")
push!(lines, "// official stations from ECA&D (jittered); home stations synthetic, shaped like the project's data.")
push!(lines, "")

ds0 = NCDataset(joinpath(NC_DIR, DAYS[1][2] * ".nc"))
lon = Float64.(ds0["x"][:]); lat = Float64.(ds0["y"][:])
land = field(ds0, "cov_mask") .> 0
urban = halve(field(ds0, "cov_urbanisation_fraction"), trues(size(land)))
water = halve(field(ds0, "cov_water_fraction"), trues(size(land)))
nx, ny = size(land) .÷ 2
push!(lines, "export const GRID = { nx: $nx, ny: $ny, fineNx: $(size(land, 1)), fineNy: $(size(land, 2)), lon0: $(lon[1]), lon1: $(lon[end]), lat0: $(lat[1]), lat1: $(lat[end]) };")
push!(lines, "/** Land mask at full resolution, row-major from the north, bit-packed (LSB first). */")
push!(lines, "export const LAND = '$(b64(bitpack(rowmajor(land))))';")
push!(lines, "/** Urban and water fraction at half resolution, 0..254. */")
push!(lines, "export const URBAN = '$(b64(quant(rowmajor(urban), 0, 1)))';")
push!(lines, "export const WATER = '$(b64(quant(rowmajor(water), 0, 1)))';")
push!(lines, "/** Temperature (°C) at half resolution: lo + byte/254·(hi − lo), 255 = not land. */")
push!(lines, "export const DAYS: Record<string, { lo: number; hi: number; t: string }> = {")
for (name, stamp) in DAYS
    ds = NCDataset(joinpath(NC_DIR, stamp * ".nc"))
    T = halve(field(ds, "mean_DryBulbTemperature_Celsius"), land)
    lo, hi = floor(minimum(filter(!isnan, T))), ceil(maximum(filter(!isnan, T)))
    push!(lines, "  $name: { lo: $lo, hi: $hi, t: '$(b64(quant(rowmajor(T), lo, hi)))' },")
    close(ds)
end
push!(lines, "};")

# Europe, 20 June 2020. Official (ECA&D) stations are public; they are only
# jittered. Home stations are synthetic: each one starts from a random real
# station, is moved several km at random and gets its temperature perturbed,
# and is rejected if it lands within MIN_KM of any real station (checked after
# quantisation). The game reports a rounded total, not the real count.
rng = MersenneTwister(2026)
exs = npzread(joinpath(EU_DIR, "cleaned_ecad_x_arr_all.npy")); eys = npzread(joinpath(EU_DIR, "cleaned_ecad_y_arr_all.npy")); ets = npzread(joinpath(EU_DIR, "cleaned_ecad_temp_arr_all.npy"))
rxs = npzread(joinpath(EU_DIR, "cleaned_x_arr_all.npy")); rys = npzread(joinpath(EU_DIR, "cleaned_y_arr_all.npy")); rts = npzread(joinpath(EU_DIR, "cleaned_temp_arr_all.npy"))
const EU = (lon0 = -11.0, lon1 = 30.0, lat0 = 35.0, lat1 = 71.5, tlo = 0.0, thi = 38.0)
const HOME_SHOWN = 24_000      # 1 in 5 of the reported total
const HOME_TOTAL = 120_000     # rounded, deliberately not the real count
const MIN_KM = 0.3
q16(v, a, b) = round(UInt16, clamp((v - a) / (b - a), 0, 1) * 65535)
unq(q, a, b) = a + q / 65535 * (b - a)
km(lon1, lat1, lon2, lat2) = hypot((lon1 - lon2) * 111.32 * cosd((lat1 + lat2) / 2), (lat1 - lat2) * 111.0)

# Grid hash of the real home stations (0.02° cells) for nearest-neighbour checks.
cell(lon, lat) = (floor(Int, lon / 0.02), floor(Int, lat / 0.02))
buckets = Dict{Tuple{Int,Int},Vector{Int}}()
for k in eachindex(rxs)
    push!(get!(buckets, cell(rxs[k], rys[k]), Int[]), k)
end
function nearest_real_km(lon, lat)
    ci, cj = cell(lon, lat)
    best = Inf
    for di in -1:1, dj in -1:1, k in get(buckets, (ci + di, cj + dj), Int[])
        best = min(best, km(lon, lat, rxs[k], rys[k]))
    end
    best
end

fake = Tuple{UInt16,UInt16,Float64}[]
while length(fake) < HOME_SHOWN
    k = rand(rng, eachindex(rxs))
    plon = rxs[k] + 0.07 * randn(rng); plat = rys[k] + 0.05 * randn(rng)
    (EU.lon0 < plon < EU.lon1 && EU.lat0 < plat < EU.lat1) || continue
    qx, qy = q16(plon, EU.lon0, EU.lon1), q16(plat, EU.lat0, EU.lat1)
    nearest_real_km(unq(qx, EU.lon0, EU.lon1), unq(qy, EU.lat0, EU.lat1)) > MIN_KM || continue
    push!(fake, (qx, qy, rts[k] + 1.0 * randn(rng)))
end
closest = minimum(nearest_real_km(unq(f[1], EU.lon0, EU.lon1), unq(f[2], EU.lat0, EU.lat1)) for f in fake)
println("synthetic home stations: ", length(fake), ", closest to a real station: ", round(closest * 1000), " m")

function pack(xs, ys, ts)
    bytes = UInt8[]
    for k in eachindex(xs)
        append!(bytes, reinterpret(UInt8, [htol(xs[k]), htol(ys[k])]))
        push!(bytes, quant([ts[k]], EU.tlo, EU.thi)[1])
    end
    bytes
end
jit(v) = v .+ 0.03 .* randn(rng, length(v))
official = pack(q16.(jit(exs), EU.lon0, EU.lon1), q16.(jit(eys), EU.lat0, EU.lat1), ets)
home = pack(first.(fake), getindex.(fake, 2), last.(fake))
push!(lines, "/** Europe, 20 June 2020: per station lon, lat (Uint16 little-endian over the box) and temperature (byte). Home stations are synthetic. */")
push!(lines, "export const EUROPE = { lon0: $(EU.lon0), lon1: $(EU.lon1), lat0: $(EU.lat0), lat1: $(EU.lat1), tlo: $(EU.tlo), thi: $(EU.thi), officialTotal: $(length(exs)), homeTotal: $(HOME_TOTAL) };")
push!(lines, "export const EUROPE_OFFICIAL = '$(b64(official))';")
push!(lines, "export const EUROPE_HOME = '$(b64(home))';")

write(OUT, join(lines, "\n") * "\n")
println("wrote ", OUT, " (", round(filesize(OUT) / 1024; digits = 1), " KiB)")
