import { pick, type Localized } from '../../lib/i18n';

interface Round { title: string; text: string; science: string }
interface Chapter { title: string; paragraphs: string[]; formula?: string }

const en = {
  storm: 'Storm!', xray: 'X-ray', startOver: 'Start over', challenge: 'Challenge',
  stop: 'Stop', play: 'Play', pause: 'Pause', next: 'Next round', total: 'See your score', watchAgain: 'Watch again',
  playAgain: 'Play again', freePlay: 'Free play',
  testStorm: (left: number) => `Test a storm (${left})`, startStorm: 'Start the storm',
  lower: 'Lower', higher: 'Higher', liveCentury: 'Live 100 years',
  scrub: 'Drag to see the storm again',
  toyHint: 'Hold on the land to pile up sand · click the sea to make waves',
  toyStormHint: 'Storm! Keep the sea away from the houses',
  warning: (s: number) => `The storm arrives in ${s}…`,
  roundHint: 'Hold and drag along the dike to build it up',
  calmHint: 'The storm is over',
  holeHint: 'Close the hole! The sea is still coming in',
  planWeakHint: 'Test storms show where the dike breaks. Then put your sand there.',
  lockedHint: 'The storm is too wild to work on the dike. Watch!',
  planHeightHint: 'Higher is safer, but costs more. Choose, then live 100 years.',
  rounds: [
    { title: 'Hold the line!', text: 'A storm is coming. Pile sand where the sea can get in — before it does, or while it does!', science: 'Most dikes fail when water pours over them and washes away the back of the dike.' },
    { title: 'Weak spots', text: 'This dike looks the same everywhere, but in some places it is rotten inside. You only have sand for a few places. Ask the computer: test a storm first!', science: 'Building dikes is expensive, so you only reinforce where they can fail. Our group worked with Deltares on computing exactly that.' },
    { title: 'How high?', text: 'Nobody knows which storms are coming. A higher dike costs more, but a flood costs even more. Choose the height, then live through 100 years.', science: 'After the 1953 flood, David van Dantzig of the Mathematisch Centrum, now CWI, worked out how high Dutch dikes should be by weighing these same costs.' },
    { title: 'Close the gate', text: 'Ships sail in and out of the harbour. When a storm comes, close the gate, but while it is shut the ships must wait. The computer forecasts each storm: 20 possible storms, surer as it comes.', science: 'The Maeslantkering near Rotterdam closes by itself when the computer forecast says the water will rise more than 3 m above NAP. It first closed for a real storm in November 2007.' },
  ] as Round[],
  go: 'Go!',
  closeGate: 'Close the gate', openGate: 'Open the gate', ships: 'Ships',
  gateHint: 'Close the gate before the water comes over the quay. Every ship that gets through earns points.',
  forecastSays: (n: number, total: number) => n ? `${n} of ${total} forecasts: water over the quay!` : `${total} forecasts: the quay stays dry`,
  forecastQuay: 'harbour quay', forecastNow: 'now',
  shipBreakdown: (dry: number, ships: number) => `🏠 ${dry} × 100  +  🚢 ${ships} × 10`,
  places: { sea: 'North Sea', land: 'Zeeland', harbour: 'Harbour' },
  roundLabel: (k: number) => `Round ${k + 1} of 4`,
  roundHeading: (dry: number, total: number) => dry === total ? `All ${total} homes stayed dry!` : `${dry} of ${total} homes stayed dry`,
  points: (n: number) => `${n} points`,
  breakdown: (dry: number, sand: number) => `🏠 ${dry} × 100  +  🟨 ${sand} sand left`,
  heightHeading: (years: number) => Number.isFinite(years) ? `Your dike fails about once every ${years} years` : 'Your dike never failed',
  heightBreakdown: (cost: number, damage: number) => `1000  −  🧱 ${cost} dike  −  🌊 ${damage} average flood damage`,
  finalHeading: 'All four rounds done!',
  finalBreakdown: (scores: number[]) => scores.map((s, k) => `Round ${k + 1}: ${s}`).join('  ·  '),
  testTitle: (peak: string) => `Test storm: ${peak} m`,
  testNothing: 'Nothing broke',
  testBroke: (n: number) => n === 1 ? 'Broke in 1 place' : `Broke in ${n} places`,
  testRunning: 'The computer is simulating…',
  forecastTitle: 'Forecast: 20 possible storms',
  fragilityTitle: 'The computer tests 6 storms against your dike',
  centuryTitle: '100 years of storms',
  yearLine: (year: number, floods: number, damage: number) => `Year ${year}  ·  floods: ${floods}  ·  damage: ${damage}`,
  average: (damage: number) => `Over many centuries the average damage is ${damage}. That average counts, not your luck.`,
  chart: { years: '100 years →', storm: 'highest storm of the year', dike: 'your dike', height: 'dike height', points: 'points', build: 'building', damage: 'floods (average)', total: 'together', best: 'best', often: 'how often', homes: 'homes flooded' },
  homes: 'Homes', sand: 'Sand', time: 'Time', dike: 'Dike', cost: 'Cost',
  breach: 'Dike breach!',
  gaugeSea: 'Sea', gaugeDike: 'Your dike',
  lens: 'What the computer sees',
  ground: 'Ground', depth: 'Water', speed: 'Flow',
  delveHeading: 'Save the Netherlands: the science',
  pour: 'Pour water', dikeHeight: 'Dike height',
  computing: (k: number, n: number) => `The computer is simulating storm ${k} of ${n}…`,
  steps: (n: number) => `This second of storm took ${n} tiny steps`,
  stepSize: (dt: string) => `each one ${dt} s long`,
  returnPeriod: (years: number) => Number.isFinite(years) ? `This dike fails about once every ${years} years` : 'This dike almost never fails',
  chapters: [
    { title: 'The land is a grid of numbers', paragraphs: [
      'The computer does not see a landscape. It sees 2 560 squares of 10 by 10 metres, and for each one it stores three numbers: how high the ground is, how deep the water is, and how fast (and which way) the water flows.',
      'The magnifying glass shows those numbers. Everything else, the houses, the grass, the waves, is paint on top.',
      'A real model of the Dutch coast uses millions of squares, some only a few metres wide.' ] },
    { title: 'Two rules for every square', paragraphs: [
      'Rule 1: water does not appear or vanish. What flows into a square minus what flows out changes how deep it is.',
      'Rule 2: water speeds up towards a lower water surface, and keeps going until something slows it down.',
      'The computer applies both rules to every square, then does it again, and again. Pour water into the tank and watch.' ],
      formula: 'new depth = depth + Δt/Δx × (in − out)\nspeeding up ∝ g × slope of the water surface' },
    { title: "Don't skip a square", paragraphs: [
      'Each step moves time forward by a tiny bit, Δt. If Δt were too big, a wave could jump over a square without the computer noticing, and the numbers would blow up.',
      'So the step is chosen so that nothing travels further than one square. Deep, fast water needs smaller steps. Send a storm and watch the count go up.' ],
      formula: 'Δt ≤ Δx / (speed + √(g × depth))' },
    { title: 'Why dikes break', paragraphs: [
      'Most dikes do not fail because they are too low for a moment. They fail when water pours over them long enough to wash away the back of the dike. Then the top collapses and the hole grows by itself.',
      'Here fast water wears the ground away: loose sand quickly, a grassy clay dike slowly. The drawing is a slice through the harbour sill.',
      'From the outside you cannot see how strong a dike is inside. That is why engineers simulate storms before deciding where to build.' ],
      formula: 'wearing away per second ∝ (speed − critical speed)²' },
    { title: 'A thousand storms', paragraphs: [
      'One simulation answers: what happens if this storm comes? But nobody knows which storms will come. So engineers ask: how often will the dike fail?',
      'The computer simulates storms of different heights against the dike (the white line: homes flooded). Measurements of the sea over many years tell how often each storm height comes (the bars).',
      'Together they give the chance of a flood in any year. Make the dike higher and watch the red bars, the storms that flood the village, get rarer.' ] },
    { title: 'Forecasts get sharper', paragraphs: [
      'A storm can be seen coming days ahead, but not exactly. So forecasters run their computer model of the North Sea many times, each time with slightly different weather. Where the runs agree, the forecast is sure; where they spread out, it is not.',
      'As the storm comes closer, the runs agree more and more. But a gate takes time to close, so you cannot wait until you are completely sure.',
      'The Maeslantkering near Rotterdam decides by itself: it closes when the forecast says the water will pass 3 metres above NAP.',
      'In this game the 20 forecasts are spread around the real storm, less and less as it comes.' ] },
    { title: 'This really happened', paragraphs: [
      'On 1 February 1953 a storm flood broke through the dikes in Zeeland and South Holland. 1 836 people died.',
      'Afterwards the government asked David van Dantzig, a mathematician and one of the founders of the Mathematisch Centrum (today CWI), how high the dikes should be. He weighed the cost of higher dikes against the chance and the cost of floods, just like round 3. His way of calculating is still used for Dutch dike safety.',
      'Our group at CWI worked with Deltares on computing how likely Dutch dikes are to fail, so that money goes where the risk is.',
      'This game leaves a lot out: wind and short waves, tides, the soil inside the dike, and it is only 640 by 400 metres.' ] },
  ] as Chapter[],
};

const T: Localized<typeof en> = {
  en,
  nl: {
    storm: 'Storm!', xray: 'Röntgen', startOver: 'Opnieuw', challenge: 'Uitdaging',
    stop: 'Stop', play: 'Afspelen', pause: 'Pauze', next: 'Volgende ronde', total: 'Naar je score', watchAgain: 'Terugkijken',
    playAgain: 'Nog een keer', freePlay: 'Vrij spelen',
    testStorm: (left: number) => `Test een storm (${left})`, startStorm: 'Start de storm',
    lower: 'Lager', higher: 'Hoger', liveCentury: 'Beleef 100 jaar',
    scrub: 'Sleep om de storm terug te zien',
    toyHint: 'Houd ingedrukt op het land voor zand · klik op de zee voor golven',
    toyStormHint: 'Storm! Houd de zee weg bij de huizen',
    warning: (s: number) => `De storm komt over ${s}…`,
    roundHint: 'Houd ingedrukt en sleep langs de dijk om hem op te hogen',
    calmHint: 'De storm is voorbij',
    holeHint: 'Dicht het gat! De zee stroomt nog steeds binnen',
    planWeakHint: 'Teststormen laten zien waar de dijk breekt. Leg daar je zand.',
    lockedHint: 'De storm is te wild om aan de dijk te werken. Kijk maar!',
    planHeightHint: 'Hoger is veiliger, maar kost meer. Kies, en beleef dan 100 jaar.',
    rounds: [
      { title: 'Houd het droog!', text: 'Er komt een storm aan. Stort zand waar de zee binnen kan komen, voordat ze komt of terwijl ze komt!', science: 'De meeste dijken bezwijken als water eroverheen stroomt en de achterkant van de dijk wegspoelt.' },
      { title: 'Zwakke plekken', text: 'Deze dijk ziet er overal hetzelfde uit, maar op sommige plekken is hij van binnen rot. Je hebt maar zand voor een paar plekken. Vraag het de computer: test eerst een storm!', science: 'Dijken bouwen is duur, dus versterk je alleen waar ze kunnen bezwijken. Onze groep rekende dat samen met Deltares uit.' },
      { title: 'Hoe hoog?', text: 'Niemand weet welke stormen er komen. Een hogere dijk kost meer, maar een overstroming kost nog meer. Kies de hoogte en beleef dan 100 jaar.', science: 'Na de watersnood van 1953 berekende David van Dantzig van het Mathematisch Centrum, nu het CWI, hoe hoog Nederlandse dijken moeten zijn, door precies deze kosten af te wegen.' },
      { title: 'Sluit de kering', text: 'Schepen varen de haven in en uit. Komt er een storm, sluit dan de kering, maar zolang die dicht is moeten de schepen wachten. De computer voorspelt elke storm: 20 mogelijke stormen, zekerder naarmate hij dichterbij komt.', science: 'De Maeslantkering bij Rotterdam sluit vanzelf als de computervoorspelling zegt dat het water meer dan 3 meter boven NAP komt. In november 2007 sloot hij voor het eerst voor een echte storm.' },
    ],
    go: 'Start!',
    closeGate: 'Sluit de kering', openGate: 'Open de kering', ships: 'Schepen',
    gateHint: 'Sluit de kering voordat het water over de kade komt. Elk schip dat erdoor komt levert punten op.',
    forecastSays: (n: number, total: number) => n ? `${n} van de ${total} voorspellingen: water over de kade!` : `${total} voorspellingen: de kade blijft droog`,
    forecastQuay: 'havenkade', forecastNow: 'nu',
    shipBreakdown: (dry: number, ships: number) => `🏠 ${dry} × 100  +  🚢 ${ships} × 10`,
    places: { sea: 'Noordzee', land: 'Zeeland', harbour: 'Haven' },
    roundLabel: (k: number) => `Ronde ${k + 1} van 4`,
    roundHeading: (dry: number, total: number) => dry === total ? `Alle ${total} huizen bleven droog!` : `${dry} van de ${total} huizen bleven droog`,
    points: (n: number) => `${n} punten`,
    breakdown: (dry: number, sand: number) => `🏠 ${dry} × 100  +  🟨 ${sand} zand over`,
    heightHeading: (years: number) => Number.isFinite(years) ? `Je dijk bezwijkt ongeveer eens per ${years} jaar` : 'Je dijk bezweek nooit',
    heightBreakdown: (cost: number, damage: number) => `1000  −  🧱 ${cost} dijk  −  🌊 ${damage} gemiddelde overstromingsschade`,
    finalHeading: 'Alle vier rondes klaar!',
    finalBreakdown: (scores: number[]) => scores.map((s, k) => `Ronde ${k + 1}: ${s}`).join('  ·  '),
    testTitle: (peak: string) => `Teststorm: ${peak} m`,
    testNothing: 'Er brak niets',
    testBroke: (n: number) => n === 1 ? 'Op 1 plek gebroken' : `Op ${n} plekken gebroken`,
    testRunning: 'De computer rekent…',
    forecastTitle: 'Voorspelling: 20 mogelijke stormen',
    fragilityTitle: 'De computer test 6 stormen tegen jouw dijk',
    centuryTitle: '100 jaar stormen',
    yearLine: (year: number, floods: number, damage: number) => `Jaar ${year}  ·  overstromingen: ${floods}  ·  schade: ${damage}`,
    average: (damage: number) => `Over heel veel eeuwen is de gemiddelde schade ${damage}. Dat gemiddelde telt, niet je geluk.`,
    chart: { years: '100 jaar →', storm: 'hoogste storm van het jaar', dike: 'jouw dijk', height: 'dijkhoogte', points: 'punten', build: 'bouwen', damage: 'overstromingen (gemiddeld)', total: 'samen', best: 'beste', often: 'hoe vaak', homes: 'huizen onder water' },
    homes: 'Huizen', sand: 'Zand', time: 'Tijd', dike: 'Dijk', cost: 'Kosten',
    breach: 'Dijkdoorbraak!',
    gaugeSea: 'Zee', gaugeDike: 'Jouw dijk',
    lens: 'Wat de computer ziet',
    ground: 'Bodem', depth: 'Water', speed: 'Stroming',
    delveHeading: 'Red Nederland: de wetenschap',
    pour: 'Water gieten', dikeHeight: 'Dijkhoogte',
    computing: (k: number, n: number) => `De computer rekent storm ${k} van ${n} door…`,
    steps: (n: number) => `Deze seconde storm kostte ${n} kleine stapjes`,
    stepSize: (dt: string) => `van elk ${dt} s`,
    returnPeriod: (years: number) => Number.isFinite(years) ? `Deze dijk bezwijkt ongeveer eens per ${years} jaar` : 'Deze dijk bezwijkt bijna nooit',
    chapters: [
      { title: 'Het land is een rooster van getallen', paragraphs: [
        'De computer ziet geen landschap. Hij ziet 2 560 vakjes van 10 bij 10 meter, en voor elk vakje onthoudt hij drie getallen: hoe hoog de grond is, hoe diep het water is, en hoe snel (en welke kant op) het water stroomt.',
        'Het vergrootglas laat die getallen zien. Al het andere, de huizen, het gras, de golven, is verf erbovenop.',
        'Een echt model van de Nederlandse kust gebruikt miljoenen vakjes, sommige maar een paar meter breed.' ] },
      { title: 'Twee regels voor elk vakje', paragraphs: [
        'Regel 1: water komt niet uit het niets en verdwijnt niet. Wat een vakje in stroomt min wat eruit stroomt, verandert hoe diep het is.',
        'Regel 2: water versnelt naar een lager wateroppervlak, en blijft doorstromen tot iets het afremt.',
        'De computer past beide regels toe op elk vakje, en dan nog eens, en nog eens. Giet water in de bak en kijk.' ],
        formula: 'nieuwe diepte = diepte + Δt/Δx × (in − uit)\nversnellen ∝ g × helling van het wateroppervlak' },
      { title: 'Sla geen vakje over', paragraphs: [
        'Elke stap zet de tijd een klein beetje vooruit, Δt. Als Δt te groot is, kan een golf over een vakje heen springen zonder dat de computer het merkt, en dan ontploffen de getallen.',
        'Daarom wordt de stap zo gekozen dat niets verder komt dan één vakje. Diep, snel water vraagt kleinere stappen. Start een storm en kijk hoe de teller oploopt.' ],
        formula: 'Δt ≤ Δx / (snelheid + √(g × diepte))' },
      { title: 'Waarom dijken breken', paragraphs: [
        'De meeste dijken bezwijken niet omdat ze even te laag zijn. Ze bezwijken als er lang genoeg water overheen stroomt om de achterkant weg te spoelen. Dan zakt de kruin in en groeit het gat vanzelf.',
        'Hier slijt snel stromend water de grond weg: los zand snel, een dijk van klei met gras langzaam. De tekening is een doorsnede door de lage drempel bij de haven.',
        'Van buiten zie je niet hoe sterk een dijk van binnen is. Daarom simuleren ingenieurs stormen voordat ze beslissen waar ze bouwen.' ],
        formula: 'wegslijten per seconde ∝ (snelheid − kritieke snelheid)²' },
      { title: 'Duizend stormen', paragraphs: [
        'Eén simulatie beantwoordt: wat gebeurt er als déze storm komt? Maar niemand weet welke stormen er komen. Dus vragen ingenieurs: hoe vaak bezwijkt de dijk?',
        'De computer simuleert stormen van verschillende hoogte tegen de dijk (de witte lijn: huizen onder water). Metingen van de zee over vele jaren vertellen hoe vaak elke stormhoogte voorkomt (de balken).',
        'Samen geven ze de kans op een overstroming in een jaar. Maak de dijk hoger en kijk hoe de rode balken, de stormen die het dorp laten overstromen, zeldzamer worden.' ] },
      { title: 'Voorspellingen worden scherper', paragraphs: [
        'Een storm zie je dagen van tevoren aankomen, maar niet precies. Daarom laten voorspellers hun computermodel van de Noordzee vele keren rekenen, elke keer met net iets ander weer. Waar de berekeningen het eens zijn, is de voorspelling zeker; waar ze uiteenlopen, niet.',
        'Hoe dichterbij de storm komt, hoe meer ze het eens worden. Maar een kering heeft tijd nodig om te sluiten, dus je kunt niet wachten tot je het helemaal zeker weet.',
        'De Maeslantkering bij Rotterdam beslist zelf: hij sluit als de voorspelling zegt dat het water hoger komt dan 3 meter boven NAP.',
        'In dit spel liggen de 20 voorspellingen rond de echte storm, steeds dichter bij elkaar naarmate hij nadert.' ] },
      { title: 'Dit is echt gebeurd', paragraphs: [
        'Op 1 februari 1953 brak een stormvloed door de dijken in Zeeland en Zuid-Holland. 1 836 mensen kwamen om.',
        'Daarna vroeg de regering David van Dantzig, wiskundige en een van de oprichters van het Mathematisch Centrum (nu het CWI), hoe hoog de dijken moesten worden. Hij woog de kosten van hogere dijken af tegen de kans op en de kosten van overstromingen, net als in ronde 3. Zijn manier van rekenen wordt nog steeds gebruikt voor de veiligheid van Nederlandse dijken.',
        'Onze groep op het CWI rekende samen met Deltares uit hoe groot de kans is dat Nederlandse dijken bezwijken, zodat het geld gaat naar waar het risico zit.',
        'Dit spel laat veel weg: wind en korte golven, eb en vloed, de grond in de dijk, en het is maar 640 bij 400 meter.' ] },
    ],
  },
  no: {
    storm: 'Storm!', xray: 'Røntgen', startOver: 'Begynn på nytt', challenge: 'Utfordring',
    stop: 'Stopp', play: 'Spill av', pause: 'Pause', next: 'Neste runde', total: 'Se poengene', watchAgain: 'Se igjen',
    playAgain: 'Spill igjen', freePlay: 'Fri lek',
    testStorm: (left: number) => `Test en storm (${left})`, startStorm: 'Start stormen',
    lower: 'Lavere', higher: 'Høyere', liveCentury: 'Lev 100 år',
    scrub: 'Dra for å se stormen igjen',
    toyHint: 'Hold inne på land for å legge sand · klikk på havet for bølger',
    toyStormHint: 'Storm! Hold havet unna husene',
    warning: (s: number) => `Stormen kommer om ${s}…`,
    roundHint: 'Hold inne og dra langs diket for å bygge det opp',
    calmHint: 'Stormen er over',
    holeHint: 'Tett hullet! Havet renner fortsatt inn',
    planWeakHint: 'Teststormer viser hvor diket brister. Legg sanden din der.',
    lockedHint: 'Stormen er for vill til å jobbe på diket. Se!',
    planHeightHint: 'Høyere er tryggere, men koster mer. Velg, og lev så 100 år.',
    rounds: [
      { title: 'Hold stand!', text: 'En storm er på vei. Legg sand der havet kan komme inn, før det kommer, eller mens det kommer!', science: 'De fleste diker svikter når vann renner over dem og vasker bort baksiden av diket.' },
      { title: 'Svake punkter', text: 'Dette diket ser likt ut overalt, men noen steder er det råttent inni. Du har bare sand til noen få steder. Spør datamaskinen: test en storm først!', science: 'Å bygge diker er dyrt, så man forsterker bare der de kan svikte. Gruppen vår regnet ut nettopp det sammen med Deltares.' },
      { title: 'Hvor høyt?', text: 'Ingen vet hvilke stormer som kommer. Et høyere dike koster mer, men en flom koster enda mer. Velg høyden, og lev så gjennom 100 år.', science: 'Etter flommen i 1953 regnet David van Dantzig ved Mathematisch Centrum, nå CWI, ut hvor høye nederlandske diker burde være, ved å veie nettopp disse kostnadene.' },
      { title: 'Steng porten', text: 'Skip seiler inn og ut av havna. Når en storm kommer, stenger du porten, men så lenge den er stengt må skipene vente. Datamaskinen varsler hver storm: 20 mulige stormer, sikrere jo nærmere den kommer.', science: 'Maeslantkering ved Rotterdam stenger av seg selv når datamaskinens varsel sier at vannet vil stige mer enn 3 meter over NAP. Den stengte for første gang for en ekte storm i november 2007.' },
    ],
    go: 'Kjør!',
    closeGate: 'Steng porten', openGate: 'Åpne porten', ships: 'Skip',
    gateHint: 'Steng porten før vannet kommer over kaia. Hvert skip som kommer gjennom gir poeng.',
    forecastSays: (n: number, total: number) => n ? `${n} av ${total} varsler: vann over kaia!` : `${total} varsler: kaia holder seg tørr`,
    forecastQuay: 'havnekai', forecastNow: 'nå',
    shipBreakdown: (dry: number, ships: number) => `🏠 ${dry} × 100  +  🚢 ${ships} × 10`,
    places: { sea: 'Nordsjøen', land: 'Zeeland', harbour: 'Havn' },
    roundLabel: (k: number) => `Runde ${k + 1} av 4`,
    roundHeading: (dry: number, total: number) => dry === total ? `Alle ${total} husene holdt seg tørre!` : `${dry} av ${total} hus holdt seg tørre`,
    points: (n: number) => `${n} poeng`,
    breakdown: (dry: number, sand: number) => `🏠 ${dry} × 100  +  🟨 ${sand} sand igjen`,
    heightHeading: (years: number) => Number.isFinite(years) ? `Diket ditt svikter omtrent én gang hvert ${years}. år` : 'Diket ditt sviktet aldri',
    heightBreakdown: (cost: number, damage: number) => `1000  −  🧱 ${cost} dike  −  🌊 ${damage} gjennomsnittlig flomskade`,
    finalHeading: 'Alle fire rundene ferdig!',
    finalBreakdown: (scores: number[]) => scores.map((s, k) => `Runde ${k + 1}: ${s}`).join('  ·  '),
    testTitle: (peak: string) => `Teststorm: ${peak} m`,
    testNothing: 'Ingenting brast',
    testBroke: (n: number) => n === 1 ? 'Brast på 1 sted' : `Brast på ${n} steder`,
    testRunning: 'Datamaskinen regner…',
    forecastTitle: 'Varsel: 20 mulige stormer',
    fragilityTitle: 'Datamaskinen tester 6 stormer mot diket ditt',
    centuryTitle: '100 år med stormer',
    yearLine: (year: number, floods: number, damage: number) => `År ${year}  ·  flommer: ${floods}  ·  skade: ${damage}`,
    average: (damage: number) => `Over mange hundreår er gjennomsnittlig skade ${damage}. Det er gjennomsnittet som teller, ikke flaksen din.`,
    chart: { years: '100 år →', storm: 'årets høyeste storm', dike: 'diket ditt', height: 'dikehøyde', points: 'poeng', build: 'bygging', damage: 'flommer (gjennomsnitt)', total: 'til sammen', best: 'best', often: 'hvor ofte', homes: 'hus under vann' },
    homes: 'Hus', sand: 'Sand', time: 'Tid', dike: 'Dike', cost: 'Kostnad',
    breach: 'Dikebrudd!',
    gaugeSea: 'Hav', gaugeDike: 'Diket ditt',
    lens: 'Det datamaskinen ser',
    ground: 'Bakke', depth: 'Vann', speed: 'Strøm',
    delveHeading: 'Redd Nederland: vitenskapen',
    pour: 'Hell vann', dikeHeight: 'Dikehøyde',
    computing: (k: number, n: number) => `Datamaskinen regner på storm ${k} av ${n}…`,
    steps: (n: number) => `Dette sekundet med storm tok ${n} små steg`,
    stepSize: (dt: string) => `hvert ${dt} s langt`,
    returnPeriod: (years: number) => Number.isFinite(years) ? `Dette diket svikter omtrent én gang hvert ${years}. år` : 'Dette diket svikter nesten aldri',
    chapters: [
      { title: 'Landet er et rutenett av tall', paragraphs: [
        'Datamaskinen ser ikke et landskap. Den ser 2 560 ruter på 10 ganger 10 meter, og for hver rute husker den tre tall: hvor høy bakken er, hvor dypt vannet er, og hvor fort (og hvilken vei) vannet renner.',
        'Forstørrelsesglasset viser de tallene. Alt annet, husene, gresset, bølgene, er maling oppå.',
        'En ekte modell av den nederlandske kysten bruker millioner av ruter, noen bare noen få meter brede.' ] },
      { title: 'To regler for hver rute', paragraphs: [
        'Regel 1: vann dukker ikke opp og forsvinner ikke. Det som renner inn i en rute minus det som renner ut, endrer hvor dyp den er.',
        'Regel 2: vann får fart mot en lavere vannflate, og fortsetter til noe bremser det.',
        'Datamaskinen bruker begge reglene på hver rute, og så igjen, og igjen. Hell vann i karet og se.' ],
        formula: 'ny dybde = dybde + Δt/Δx × (inn − ut)\nfart øker ∝ g × hellingen på vannflaten' },
      { title: 'Ikke hopp over en rute', paragraphs: [
        'Hvert steg flytter tiden litt fram, Δt. Hvis Δt var for stor, kunne en bølge hoppe over en rute uten at datamaskinen merket det, og tallene ville eksplodere.',
        'Derfor velges steget slik at ingenting kommer lenger enn én rute. Dypt, raskt vann trenger mindre steg. Send en storm og se telleren gå opp.' ],
        formula: 'Δt ≤ Δx / (fart + √(g × dybde))' },
      { title: 'Hvorfor diker brister', paragraphs: [
        'De fleste diker svikter ikke fordi de er for lave et øyeblikk. De svikter når vann renner over dem lenge nok til å vaske bort baksiden. Da raser toppen sammen, og hullet vokser av seg selv.',
        'Her sliter raskt vann bort bakken: løs sand fort, et dike av leire med gress sakte. Tegningen er et snitt gjennom den lave terskelen ved havna.',
        'Utenfra kan man ikke se hvor sterkt et dike er inni. Derfor simulerer ingeniører stormer før de bestemmer hvor de skal bygge.' ],
        formula: 'slitasje per sekund ∝ (fart − kritisk fart)²' },
      { title: 'Tusen stormer', paragraphs: [
        'Én simulering svarer på: hva skjer hvis denne stormen kommer? Men ingen vet hvilke stormer som kommer. Så ingeniører spør: hvor ofte svikter diket?',
        'Datamaskinen simulerer stormer av ulik høyde mot diket (den hvite linjen: hus under vann). Målinger av havet gjennom mange år forteller hvor ofte hver stormhøyde kommer (søylene).',
        'Sammen gir de sjansen for en flom et gitt år. Gjør diket høyere og se de røde søylene, stormene som setter landsbyen under vann, bli sjeldnere.' ] },
      { title: 'Varslene blir skarpere', paragraphs: [
        'En storm kan sees dager i forveien, men ikke nøyaktig. Derfor kjører varslerne datamodellen sin av Nordsjøen mange ganger, hver gang med litt forskjellig vær. Der kjøringene er enige, er varselet sikkert; der de sprer seg, er det ikke.',
        'Jo nærmere stormen kommer, jo mer enige blir de. Men en port trenger tid på å stenge, så man kan ikke vente til man er helt sikker.',
        'Maeslantkering ved Rotterdam bestemmer selv: den stenger når varselet sier at vannet vil gå over 3 meter over NAP.',
        'I dette spillet ligger de 20 varslene rundt den ekte stormen, tettere og tettere jo nærmere den kommer.' ] },
      { title: 'Dette skjedde virkelig', paragraphs: [
        '1. februar 1953 brøt en stormflo gjennom dikene i Zeeland og Sør-Holland. 1 836 mennesker døde.',
        'Etterpå spurte regjeringen David van Dantzig, matematiker og en av grunnleggerne av Mathematisch Centrum (i dag CWI), hvor høye dikene burde være. Han veide kostnaden ved høyere diker mot sjansen for og kostnaden ved flom, akkurat som i runde 3. Hans måte å regne på brukes fortsatt for sikkerheten til nederlandske diker.',
        'Gruppen vår ved CWI regnet sammen med Deltares ut hvor sannsynlig det er at nederlandske diker svikter, slik at pengene går dit risikoen er.',
        'Dette spillet utelater mye: vind og korte bølger, tidevann, jorda inni diket, og det er bare 640 ganger 400 meter.' ] },
    ],
  },
};
export const text = () => pick(T);
