import { pick, type Localized } from '../../lib/i18n';
const en = {
  storm: 'Storm!', computer: 'Computer view', landscape: 'Landscape', startOver: 'Start over', challenge: 'Challenge',
  stop: 'Stop', play: 'Play', pause: 'Pause', playAgain: 'Play again', watchAgain: 'Watch again', freePlay: 'Free play',
  replay: 'Replay', scrub: 'Drag to see the storm again',
  toyHint: 'Hold on the land to pile up sand · click the sea to make waves',
  toyStormHint: 'Storm! Keep the sea away from the houses',
  introTitle: 'Hold the line!',
  introText: 'A storm is coming. Pile sand wherever the sea can get in, before it does. Every dry house and every bag of sand you keep earns points.',
  go: 'Go!',
  warning: (s: number) => `The storm arrives in ${s}…`,
  roundHint: 'Hold and drag along the dike to build it up',
  calmHint: 'The storm is over',
  holeHint: 'Close the hole! The sea is still coming in',
  breach: 'Dike breach!',
  gaugeSea: 'Sea', gaugeDike: 'Your dike',
  homes: 'Homes', sand: 'Sand', time: 'Time',
  resultHeading: (dry: number, total: number) => dry === total ? `All ${total} homes stayed dry!` : `${dry} of ${total} homes stayed dry`,
  points: (n: number) => `${n} points`,
  breakdown: (dry: number, sand: number) => `🏠 ${dry} × 100  +  🟨 ${sand} sand left`,
  ground: 'Ground', depth: 'Water', speed: 'Flow',
};
const T: Localized<typeof en> = {
  en,
  nl: {
    storm: 'Storm!', computer: 'Computerbeeld', landscape: 'Landschap', startOver: 'Opnieuw', challenge: 'Uitdaging',
    stop: 'Stop', play: 'Afspelen', pause: 'Pauze', playAgain: 'Nog een keer', watchAgain: 'Terugkijken', freePlay: 'Vrij spelen',
    replay: 'Terugkijken', scrub: 'Sleep om de storm terug te zien',
    toyHint: 'Houd ingedrukt op het land voor zand · klik op de zee voor golven',
    toyStormHint: 'Storm! Houd de zee weg bij de huizen',
    introTitle: 'Houd het droog!',
    introText: 'Er komt een storm aan. Stort zand waar de zee binnen kan komen, voordat ze dat doet. Elk droog huis en elke zak zand die je overhoudt levert punten op.',
    go: 'Start!',
    warning: (s: number) => `De storm komt over ${s}…`,
    roundHint: 'Houd ingedrukt en sleep langs de dijk om hem op te hogen',
    calmHint: 'De storm is voorbij',
    holeHint: 'Dicht het gat! De zee stroomt nog steeds binnen',
    breach: 'Dijkdoorbraak!',
    gaugeSea: 'Zee', gaugeDike: 'Jouw dijk',
    homes: 'Huizen', sand: 'Zand', time: 'Tijd',
    resultHeading: (dry: number, total: number) => dry === total ? `Alle ${total} huizen bleven droog!` : `${dry} van de ${total} huizen bleven droog`,
    points: (n: number) => `${n} punten`,
    breakdown: (dry: number, sand: number) => `🏠 ${dry} × 100  +  🟨 ${sand} zand over`,
    ground: 'Bodem', depth: 'Water', speed: 'Stroming',
  },
  no: {
    storm: 'Storm!', computer: 'Datamaskinbilde', landscape: 'Landskap', startOver: 'Begynn på nytt', challenge: 'Utfordring',
    stop: 'Stopp', play: 'Spill av', pause: 'Pause', playAgain: 'Spill igjen', watchAgain: 'Se igjen', freePlay: 'Fri lek',
    replay: 'Se igjen', scrub: 'Dra for å se stormen igjen',
    toyHint: 'Hold inne på land for å legge sand · klikk på havet for bølger',
    toyStormHint: 'Storm! Hold havet unna husene',
    introTitle: 'Hold stand!',
    introText: 'En storm er på vei. Legg sand der havet kan komme inn, før det gjør det. Hvert tørt hus og hver sekk sand du sparer gir poeng.',
    go: 'Kjør!',
    warning: (s: number) => `Stormen kommer om ${s}…`,
    roundHint: 'Hold inne og dra langs diket for å bygge det opp',
    calmHint: 'Stormen er over',
    holeHint: 'Tett hullet! Havet renner fortsatt inn',
    breach: 'Dikebrudd!',
    gaugeSea: 'Hav', gaugeDike: 'Diket ditt',
    homes: 'Hus', sand: 'Sand', time: 'Tid',
    resultHeading: (dry: number, total: number) => dry === total ? `Alle ${total} husene holdt seg tørre!` : `${dry} av ${total} hus holdt seg tørre`,
    points: (n: number) => `${n} poeng`,
    breakdown: (dry: number, sand: number) => `🏠 ${dry} × 100  +  🟨 ${sand} sand igjen`,
    ground: 'Bakke', depth: 'Vann', speed: 'Strøm',
  },
};
export const text = () => pick(T);
