import { pick, type Localized } from '../../lib/i18n';
const en = {
  subtitle:'BEAT THE STORM', storm:'Send the storm', rewind:'Exit simulation', undo:'Undo', reset:'Reset',
  cancel:'Cancel', playback:'Playback', back:'Back 5 seconds', forward:'Forward 5 seconds', more:'More', scenario:'Challenge', surgeMode:'Storm surge', wavesMode:'Three waves',
  surgeDescription:'The sea rises, stays high, then retreats. Keep it outside your dike.',
  wavesDescription:'Three waves arrive in succession. Watch them travel and spill over low defenses.',
  systemHint:'Dikes keep the sea out. A canal collects water in the pond, where an automatic pump maintains the water level. A flood can arrive faster than the pump can remove it. Hold to add sand; a slower stroke builds higher. The posts show local water depth.',
  pause:'Pause', resume:'Continue', fast:'Fast ×4', model:'From above', landscape:'3D view',
  scrub:'Explore the flood and drainage', calculating:'Calculating the flood…', calculationFailed:'Could not finish the simulation. Try a fresh landscape.',
  homes:'Kept dry', budget:'Sand', draw:'Hold to raise sand. Drag slowly to build a dike.',
  ended:'Try a different defense, or explore the timeline.', safe:'Every home stayed dry.',
  recoveryHint:'The sea is retreating. The pond and pump continue draining the polder.',
  running:'Watch the water, or drag the timeline to explore.', recovery:'Drainage', stormTime:'Storm', ready:'Shape your defense',
  ground:'Ground', depth:'Water depth', speed:'Flow speed', pumpRate:'Pump flow', slice:'SECTION THROUGH THE LOW DIKE · HEIGHT EXAGGERATED',
};
const T: Localized<typeof en> = {
  en,
  nl: {
    subtitle:'VERSLA DE STORM', storm:'Start de storm', rewind:'Simulatie verlaten', undo:'Ongedaan', reset:'Begin opnieuw',
    cancel:'Annuleren', playback:'Afspelen', back:'5 seconden terug', forward:'5 seconden vooruit', more:'Meer', scenario:'Uitdaging', surgeMode:'Stormvloed', wavesMode:'Drie golven',
    surgeDescription:'De zee stijgt, blijft hoog en zakt weer. Houd het water buiten je dijk.',
    wavesDescription:'Drie golven komen na elkaar. Zie hoe ze bewegen en over lage dijken stromen.',
    systemHint:'Dijken houden de zee tegen. Een sloot verzamelt water in de vijver, waar een automatisch gemaal het peil regelt. Bij een overstroming kan water sneller binnenkomen dan de pomp het afvoert. Houd ingedrukt om zand toe te voegen; langzaam slepen bouwt hoger. De palen tonen de lokale waterdiepte.',
    pause:'Pauze', resume:'Verder', fast:'Snel ×4', model:'Van boven', landscape:'3D-weergave',
    scrub:'Bekijk de overstroming en afwatering', calculating:'Overstroming berekenen…', calculationFailed:'De simulatie kon niet worden voltooid. Probeer een nieuw landschap.',
    homes:'Droog gebleven', budget:'Zand', draw:'Houd ingedrukt om zand toe te voegen. Sleep langzaam voor een hogere dijk.',
    ended:'Probeer een andere verdediging of bekijk de tijdlijn.', safe:'Alle huizen bleven droog.',
    recoveryHint:'De zee zakt. De vijver en het gemaal blijven de polder ontwateren.',
    running:'Volg het water of sleep de tijdlijn.', recovery:'Afwatering', stormTime:'Storm', ready:'Bouw je verdediging',
    ground:'Bodem', depth:'Waterdiepte', speed:'Stroomsnelheid', pumpRate:'Pompdebiet', slice:'DOORSNEDE DOOR DE LAGE DIJK · HOOGTE OVERDREVEN',
  },
  no: {
    subtitle:'SLÅ STORMEN', storm:'Start stormen', rewind:'Avslutt simuleringen', undo:'Angre', reset:'Begynn på nytt',
    cancel:'Avbryt', playback:'Avspilling', back:'5 sekunder tilbake', forward:'5 sekunder frem', more:'Mer', scenario:'Utfordring', surgeMode:'Stormflo', wavesMode:'Tre bølger',
    surgeDescription:'Havet stiger, holder seg høyt og trekker seg tilbake. Hold vannet utenfor diket.',
    wavesDescription:'Tre bølger kommer etter hverandre. Se dem bevege seg og strømme over lave diker.',
    systemHint:'Diker holder havet ute. En kanal samler vann i dammen, der en automatisk pumpe regulerer vannstanden. En flom kan komme raskere enn pumpen klarer å fjerne vannet. Hold inne for å legge sand; langsomme strøk bygger høyere. Stolpene viser lokal vanndybde.',
    pause:'Pause', resume:'Fortsett', fast:'Raskt ×4', model:'Ovenfra', landscape:'3D-visning',
    scrub:'Utforsk flommen og dreneringen', calculating:'Beregner flommen…', calculationFailed:'Simuleringen kunne ikke fullføres. Prøv et nytt landskap.',
    homes:'Holdt tørre', budget:'Sand', draw:'Hold inne for å legge sand. Dra langsomt for å bygge høyere.',
    ended:'Prøv et annet forsvar, eller utforsk tidslinjen.', safe:'Alle husene holdt seg tørre.',
    recoveryHint:'Havet trekker seg tilbake. Dammen og pumpen fortsetter å drenere polderen.',
    running:'Følg vannet, eller dra i tidslinjen.', recovery:'Drenering', stormTime:'Storm', ready:'Bygg forsvaret',
    ground:'Bakke', depth:'Vanndybde', speed:'Strømhastighet', pumpRate:'Pumpeføring', slice:'SNITT GJENNOM DET LAVE DIKET · OVERDREVET HØYDE',
  },
};
export const text = () => pick(T);
